### ISSUE TITLE
Detect if Nullable is enabled for project, and set it automatically

### ISSUE THREAD

**Issue by ErikEJ** [ErikEJ/EFCorePowerTools#1164]
https://github.com/dotnet/efcore/commit/fd599b2601015da4a23daee71764f47b455dfbb7#diff-089618fa90513063948c8462228f6706ba8ac8b5765c593599c2c79f5d475154R1284

**Comment by ErikEJ** [comment]
Not sure I understand why?

**Comment by MisinformedDNA** [comment]
Because my project had nullable enabled, but the tools generated classes with nullable disabled. Having all the classes suddenly nullable enabled causes a lot of warnings that I'm just not ready to deal with. So I disable nullable at the project level, so that the classes generate with nullable disabled.

**Comment by ErikEJ** [comment]
Which .net and EF Core version?

**Comment by ErikEJ** [comment]
I have reverted in the latest daily, please let me know if that solves your issue.

**Comment by ErikEJ** [comment]
@MisinformedDNA Ping?

**Comment by MisinformedDNA** [comment]
Sorry, I didn't get back to you sooner. I had a major release this week, but it looks like you already pushed it. Thanks.
