### ISSUE TITLE
Add ability to not generate M2M scaffolding with EF Core 6

### ISSUE THREAD

**Issue by ErikEJ** [ErikEJ/EFCorePowerTools#1184]
https://github.com/dotnet/efcore/blob/fb61eb7cfb75253fbae93aeac23c404ba68b83a8/src/EFCore.Design/Scaffolding/Internal/RelationalScaffoldingModelFactory.cs#L658-L660

Override and bypass whole code to detect M2M.

**Comment by janseris** [comment]
Maybe a combination of the current EF Core 6 state with option "also explicitly generate join tables" would be nice

**Comment by ErikEJ** [comment]
Yes, this is what this feature is about!

**Comment by ErikEJ** [comment]
This is now available as an advanced option in the latest daily build

**Comment by Timothy-Siford** [comment]
I am not entirely sure where to ask this question so I apologize if this is the wrong location.

I want to keep the M2M scaffolding so that I don't have to work with the middle/translational entity.  Awesome.  Simply keep the option entitled "Use many to many entity (EF Core 6)" under Advanced... as *not* checked.  That said, when choosing this approach, I am presented with generated code that does not build unless I change it.  Here is a very simple example to demonstrate my point.

User Table with Id, Name
Role Table with Id, Name
UserRole Table with UserId, RoleId (UserId being a FK to User.Id and RoleId being an FK to Role.Id)

When generating the code I get the following at the end of the generated User.cs file ...
[ForeignKey(nameof(UserId))]
[InverseProperty(nameof(Role.Users))]
public virtual ICollection<Role> Roles { get; set; }

The line [ForeignKey(nameof(UserId))] does not recognize UserId (the normal red squiggly line in the Visual Studio IDE with the requisite message being "The name 'UserId' does not exist in the current context" .  However, if I change the entire line manually to [ForeignKey("UserId")] then everything builds with no issue.

The same is true for the Role table.  When generating the code I get the following at the end of the generated Role.cs file ...
[ForeignKey(nameof(RoleId))]
[InverseProperty(nameof(User.Roles))]
public virtual ICollection<User> Users { get; set; }

The line [ForeignKey(nameof(RoleId))] does not recognize RoleId.

What am I missing here?  I feel like there is probably some simple configuration or setup that I am missing that will allow the scaffolding to work as designed.

**Comment by janseris** [comment]
> I am not entirely sure where to ask this question so I apologize if this is the wrong location.
> 
> I want to keep the M2M scaffolding so that I don't have to work with the middle/translational entity. Awesome. Simply keep the option entitled "Use many to many entity (EF Core 6)" under Advanced... as _not_ checked. That said, when choosing this approach, I am presented with generated code that does not build unless I change it. Here is a very simple example to demonstrate my point.
> 
> User Table with Id, Name Role Table with Id, Name UserRole Table with UserId, RoleId (UserId being a FK to User.Id and RoleId being an FK to Role.Id)
> 
> When generating the code I get the following at the end of the generated User.cs file ... [ForeignKey(nameof(UserId))] [InverseProperty(nameof(Role.Users))] public virtual ICollection Roles { get; set; }
> 
> The line [ForeignKey(nameof(UserId))] does not recognize UserId (the normal red squiggly line in the Visual Studio IDE with the requisite message being "The name 'UserId' does not exist in the current context" . However, if I change the entire line manually to [ForeignKey("UserId")] then everything builds with no issue.
> 
> The same is true for the Role table. When generating the code I get the following at the end of the generated Role.cs file ... [ForeignKey(nameof(RoleId))] [InverseProperty(nameof(User.Roles))] public virtual ICollection Users { get; set; }
> 
> The line [ForeignKey(nameof(RoleId))] does not recognize RoleId.
> 
> What am I missing here? I feel like there is probably some simple configuration or setup that I am missing that will allow the scaffolding to work as designed.

Does this just mean that you ticked the option to generate annotations and they are wrongly generated (by EF Power Tools)?

**Comment by ErikEJ** [comment]
@Timothy-Siford Please create a new issue and provide a sample SQL script, and/or a repro project (incl SQL script) and I will have a look.

**Comment by ErikEJ** [comment]
@Timothy-Siford which EF Core version?

**Comment by Timothy-Siford** [comment]
My teammate decided to jump on this and discovered that it's a combination of enabling both Data Annotations and Handlebars (C#).

DataAnnotations adds the  [ForeignKey("UserId")] 
Handlebars (C#) changes this to [ForeignKey(nameof(UserId))]

A member of our team had added the Handlebars option awhile ago in preparation for something that was never pursued on this project.  When we turn handlebars off, we get [ForeignKey("UserId")] which works perfectly.

My teammate does have a test project that shows the issue ... but given that we don't need handlebars, we can turn that off and be good to go.

**Comment by Timothy-Siford** [comment]
Oh! We're using EF Core v6.0.9

**Comment by nathanpovo** [comment]
In case anyone else was trying to find how to use this feature, the option to enable this is called "Use many to many entity"

![image](https://github.com/ErikEJ/EFCorePowerTools/assets/17831160/236ed397-a8ac-4965-ab3c-9666f22e39e7)

For the CLI version, set the `use-many-to-many-entity` option to `true`

![image](https://github.com/ErikEJ/EFCorePowerTools/assets/17831160/ff200a45-1fc5-47d0-ae25-b1f9837a1a96)

Link to the documentation https://github.com/ErikEJ/EFCorePowerTools/wiki/Reverse-Engineering#code-generation
