### ISSUE TITLE
Question about how to update Tonys Sneed  EntityFrameworkCore.Scaffolding.Handlebars 

### ISSUE THREAD

**Issue by RaulFunezp** [ErikEJ/EFCorePowerTools#1257]
Hello Erik,
What should I do to integrate the latest release (v6.0.3) of tonysneed EntityFrameworkCore.Scaffolding.Handlebars to your reverse engineering EFCorePowerTools using Handlebars templates ?

I hope that this release solves the HasKey not generated problem that I have.  I tried reverse engineering using HandleBars templates after the release was published but not avail.  I also tried to uninstall/install the EFCorePowerTools with no success either.

It may be that this release has not solved my problem but I must be sure that it is being applied during reverse engineering using Handlebars templates but I do not know how to be sure of that.  Thank you for your great tool that is very useful for all of us.

**Comment by ErikEJ** [comment]
I need to update the tool, as the Handlebars library is an external dependency. I have just done that, and the fix is available in the latest daily build.

Glad that you appreciate this free tool and the free support you get from me and @tonysneed 

The tool and GitHub based support is free, but I would be very grateful for a [rating or review here](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools#review-details), and I also appreciate [sponsorships](https://github.com/sponsors/ErikEJ)

**Comment by RaulFunezp** [comment]
I'll do both in a couple of days. Thanks again.

**Comment by tonysneed** [comment]
I added tests to my Handlebars library to ensure the fix works and doesn't break anything else. 🤠

**Comment by RaulFunezp** [comment]
That’s nice.  Thank you very much.
