### ISSUE TITLE
How to troubleshoot Reverse Engineering Errors

### ISSUE THREAD

**Issue by nssidhu** [ErikEJ/EFCorePowerTools#1455]
When i try to reverse Engineer i get the following Errors

Unable to get result set shape for PROCEDURE 'dbo.sp_DeleteOrgLocationCategory'.
Incorrect syntax near 'SEQUENCE'.
I have a statement like this, **not sure what the problem is here**
```
  DECLARE @SequsenceName varchar(100);
 EXECUTE ('DROP SEQUENCE ' + @SequsenceName) WITH RESULT SETS NONE;
```

Unable to get result set shape for PROCEDURE 'dbo.sp_GetToken'.
'geography::Point' failed because parameter 1 is not allowed to be null.
```
DECLARE @Latitude DECIMAL(12,9),
DECLARE	@Longitude DECIMAL(12,9),
Declare @UserLocation geography = geography::Point(@Latitude,@Longitude, 4326);
```
**Not sure what is wrong here either?**

Unable to get result set shape for PROCEDURE 'dbo.sp_GetTempToken'.
Incorrect syntax near '.'.
**(I have no clue where in my code this is referring to)**

I am able to run those stored procedure successfully without any issue in SSMS.
How do i go about troubleshooting the reported Errors?

Secondly, I happen to Reformat my VM and reinstalled VS 2022 along with EF Power Tool Extension.
 All these was working earlier, not sure if some default settings have changed in the new version of EF Power tool.

**Comment by ErikEJ** [comment]
The reason you did not see the errors earlier were due to a bug! So they were always there..

Basically, please [read the docs](https://github.com/ErikEJ/EFCorePowerTools/wiki/Reverse-Engineering#sql-server-stored-procedures) - you may have luck with `"UseLegacyResultSetDiscovery": true` for some of the failing ones.

Regarding the quality of the error messages - I pass on what the SQL Server returns, so I cannot improve that.

**Comment by ErikEJ** [comment]
I also gave you some troubleshooting advice here, which is still appliclable (when using "UseLegcayResultSetDiscovery" #1208

**Comment by nssidhu** [comment]
"UseLegacyResultSetDiscovery": true 
helped

**Comment by ErikEJ** [comment]
Great!
