### ISSUE TITLE
Reworked PickServerTablesDialog issue

### ISSUE THREAD

**Issue by ErikEJ** [ErikEJ/EFCorePowerTools#147]
@Herdo Latest master (working fine with VS 15.9!!)

When clicking the Tables checkbox at the top, I expect the selection of all table to toggle accordingly, but the checkbox is tristate, so I have to click twice.

**Comment by Herdo** [comment]
This is because the "master" checkbox is also updated by the individual checkboxes.
- If there are two tables, and both are selected, the "master" will also be selected.
- If there are two tables, and none are selected, the "master" will also be un-selected.
- If there are two tables, and only one is selected, the "master" will show the intermediate state.

On the other hand, the "master" checkbox handles selecting the individual checkboxes:
- If the "master" goes to selected, all individual checkboxes are checked.
- If the "master" goes to un-selected, all individual checkboxes are un-checked.
- If the "master" goes to intermediate state, nothing happens.

I'd have to search for a solution to solve the last bullet point, without breaking the other five points.

**Comment by ErikEJ** [comment]
Maybe drop the Update of the Master checkbox?

**Comment by ErikEJ** [comment]
Thanks!
