### ISSUE TITLE
Add UI to edit efpt.renaming.json

### ISSUE THREAD

**Issue by ErikEJ** [ErikEJ/EFCorePowerTools#152]
Add optional wizard step to edit and save the file.

With column list from live database!

And add wiki post, see #188

**Comment by ErikEJ** [comment]
Not something I plan to do

**Comment by sm15455** [comment]
Could we re-open this?

**Comment by ErikEJ** [comment]
@sm15455 wrote:

Exactly.
I was thinking it could be done in two ways:

In the current tree we add a small icon next to tables and column name. When the user clicks on the icon, a textbox appears next to the name and let the user enter the new name.

Do something similar to previous solution, but in a new wizard screen.

**Comment by sm15455** [comment]
![image](https://user-images.githubusercontent.com/5398631/100498342-dcbe9b80-3161-11eb-8d6c-098a2e24c683.png)

I made some experiment and this is a very early preview UI. 

However I have a problem. Tables in the renaming file are grouped by schema. Each schema has the UseSchemaName property. Since in the TreeView we don't group by schema, there's no correct place to show this flag to user. 
I can think of three different ways to solve this problem:

1. Add the schema level in TreeView and group objects by schema.
2. Create a new page after objects selection dedicated to objects renaming where we can group objects the way we need (we could add a skip.
3. Allow the renaming file to contain multiple items for the same schema (it's already possible). Add a checkbox for each table/view/sp/function to let user set UseSchemaName property. Change GetSchema method in ReplacingCandidateNamingService to search all items by schema name (now it returns only the first one).

First and third option are not complicated from a technical point of view, but would make TreeView even more cluttered than in the image. Maybe it would get the user more confused.
Second option is not complicated from a technical point of view and has the advantage of leaving TreeView clean but would add a new step that most of user don't need. We could change navigation buttons in the objects selection page like this: Go to options, Go to renaming, Cancel.

**Comment by ErikEJ** [comment]
How about the ability to simply press F2 on the item (table name or column name), and then provide a textbox for entry of the new name? (That would of course require a new schema level for tables and views in the tree view)

And then the displayname could be something like "UserDefinedName [OriginalName]" ?

Dont worry too much about UseSchemaName, I think support for that can be skipped in first iteration.

But first we must prepare for this:

- Extend TableModel to include schema (can be null) and name instead of the constructed name.
- Add support for multiple renaming.json files (to go in tandem with support for multiple efpt.config.json files)
- Redesign current display of tables and views to include a schema level

Once these changes are in (via one or even multiple PRs) , we are in a much better position to support renaming from the UI, I think.

**Comment by sm15455** [comment]
> How about the ability to simply press F2 on the item (table name or column name), and then provide a textbox for entry of the new name? (That would of course require a new schema level for tables and views in the tree view)
> 
> And then the displayname could be something like "UserDefinedName [OriginalName]" ?

I like that :)

> Dont worry too much about UseSchemaName, I think support for that can be skipped in first iteration.
> 
ok

> But first we must prepare for this:
> 
>     * Extend TableModel to include schema (can be null) and name instead of the constructed name.

It should be easy, just have to figure if it breaks something.

>     * Add support for multiple renaming.json files (to go in tandem with support for multiple efpt.config.json files)

This is something I would need help or maybe you could do.
 
>     * Redesign current display of tables and views to include a schema level

This is not a problem once point 1 is completed.

> Once these changes are in (via one or even multiple PRs) , we are in a much better position to support renaming from the UI, I think.

You are right. If you could take care of point two, I could later work on the others

**Comment by ErikEJ** [comment]
I can have a look at both 1 and 2 above. Will ping you when I start work one either one of them

**Comment by ErikEJ** [comment]
First one is done, PR in. Started work on the second one...

**Comment by ErikEJ** [comment]
@sm15455 Item 2 is done now

**Comment by sm15455** [comment]
Great! I'll start working on the UI side in a couple of days.

**Comment by sm15455** [comment]
![image](https://user-images.githubusercontent.com/5398631/101239426-b5c71300-36e7-11eb-99ee-02a5f3cdb504.png)
![image](https://user-images.githubusercontent.com/5398631/101239433-c4152f00-36e7-11eb-93bc-3034f64ff5d5.png)

The work is almost done. There's two things I'm missing:

1. I return the custom replacing information but no efpt.renaming.json is created (I haven't investigated but I guess it has to be done from scratch).
2. Schema class has properties about regex replacing. How do we let the user edit them? Maybe the schema could be an hyperlink that opens a new dialog?

**Comment by ErikEJ** [comment]
Amazing!

I will take care of persisting the result. Do you read any pre-existing info?

**Comment by ErikEJ** [comment]
I have to think a little about the regex properties...

**Comment by ErikEJ** [comment]
Let's descope the regex part for now, just must be sure it is preserved after editing.

**Comment by sm15455** [comment]
> I will take care of persisting the result. Do you read any pre-existing info?

Yes. The PickTableDialog now accepts the schema returned by the call to CustomNameOptionsExtensions.TryRead(renamingPath, optionsPath); The dialog then return the modified schema (preserving existing options) to the ReverseEngineerHandler wich in turn puts the returned schema in the CustomReplacers property of ReverseEngineerOptions class. 

> Let's descope the regex part for now, just must be sure it is preserved after editing.

Ok
