### ISSUE TITLE
9 second delay getting project properties for Xamarin Android Project 

### ISSUE THREAD

**Issue by mludlum** [ErikEJ/EFCorePowerTools#1542]
I have an Xamarin Android project in a solution where I'm not using EF.  If I right-click the project to build, there is a 9 second delay before I get the menu.  Visual Studio 2022 (17.3.6, but also in 17.3.3) claims its EF Core Power Tools fault.  I disabled the extension and the delay issue goes away.

Let me know if I can provide anything else for you.

**Comment by ErikEJ** [comment]
A sample solution and instructions about required VS components would be helpful.

**Comment by ErikEJ** [comment]
Let me have a look - but debugging should be easy - just press F5 on the EFCorePowertools project

**Comment by ErikEJ** [comment]
I implemented a fix for this in the [latest daily build](https://www.vsixgallery.com/extension/f4c4712c-ceae-4803-8e52-0e2049d5de9f), would be grateful if you could try it out.

I would be very grateful for a rating or review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details)

It was caused by the Android project calling into the extension 6 times on a right click, combined with the recent addition of a semi-heavy check - I have simply removed the check.

**Comment by mludlum** [comment]
Tested latest daily build.  Project settings opens up quickly now.  Thanks!
