### ISSUE TITLE
EDMX migration support

### ISSUE THREAD

**Issue by ErikEJ** [ErikEJ/EFCorePowerTools#1572]
Generate prooperty and navigation renaming files based on a an existing EDMX file -  basically, the user has to edit nothing by hand in order to migrate from EF6 Classic.

A package to do this is being worked on by @R4ND3LL 

Suggestion for UI: Add an option to the Naming section to pick an EDMX from disk

Rough proposal:

![image](https://user-images.githubusercontent.com/4169187/200161891-bcd98286-19bd-4261-8b46-ea2cab638996.png)

**Comment by R4ND3LL** [comment]
Question:  With addition to the Naming section, does this imply that the option will be saved in the efpt.config.json file and EDMX rule gen would be executed on every Reverse Engineer?

If so, this is not how I see the primary workflow.  I may be misunderstanding it, but in any case, I'll explain how I see the main database first lifecycle as it relates to EDMX support:

1. When a person initially upgrades from EF to EFC, we can assume that the database and EDMX are in sync.  
2. The user will use your VSIX to select the EDMX and generate the initial rule set.  This will include the table and column renaming file, property renaming file (navigations), and enum mapping file.
3. Then the user executes Reverse Engineer to create the database first model AND automatically apply the rules from the json files.
4. Soon after, database changes are made.  Therefore, the actual schema model has diverged from the EDMX model.  The EDMX is stale and can be discarded.  Rules generation will not be run again from the old EDMX.
5. If the user wants to apply custom naming to **new** database elements, they can modify the json rules directly.
6. User executes Reverse Engineer and the rules are automatically applied again.
7. Items 4-6 above repeat forever.

Since we don't want to force the user to maintain the EDMX, the rule generation should be an independent function available outside the Reverse Engineer flow.  

The rule generation option can still be included in the Reverse Engineer flow as automated support for the **secondary workflow** where the user maintains the EDMX going forward so that they never have to edit any rules by hand.

Although I personally would like to see the EDMX deleted after the rules are initially extracted.

Does that make sense?  Thoughts?

**Comment by ErikEJ** [comment]
Ah! Makes sense. Then it should just be a separate menu item to create the renaming files with a dialog with an explanation and a file picker. And no persistence other than the generated renaming files. And maybe refuse to run if the files already exists.

**Comment by 2xRon** [comment]
I'd like to push back on deleting the EDMX after running the generators. Since we will be maintaining both a EF6 and EF7 versions, it will be useful be able to use the EDMX as an automated source of truth. We are currently generating the "tables" section of the config.json and the renaming.json from the EDMX file. This final piece, navigation-renaming.json (which is awesome, exciting work, ty!) will finally close the loop on a db-first with EDMX workflow.

**Comment by R4ND3LL** [comment]
@2xRon, each time you update your EDMX you will still be able to use the "Generate Rules From EDMX" menu option that @ErikEJ will provide.    Manually run that, then Reverse Engineer.

However, if it makes sense for your workflow, perhaps @ErikEJ can also add the rule gen option in-line with the Reverse Engineer (as in his original proposal above).  This is a good convenience option for that workflow to save a step.

**Comment by R4ND3LL** [comment]
EdmxRuler alpha version is up.  Just updated moments ago: https://www.nuget.org/packages/EdmxRuler/

This update has had a lot more testing.

Install CLI by:
> dotnet tool install --global EdmxRuler --version 1.0.1-alpha.0.6

@ErikEJ, you can pull in this nuget package version and start wiring it up.  The API is simple.

For rule generation use type:
> EdmxRuler.Generator.RuleGenerator

For applying rules use:
> EdmxRuler.Applicator.RuleApplicator

I will update docs soon. Let me know if you have questions.

**Comment by ErikEJ** [comment]
Implementation proposal:

Only .NET 6 / 7 projects are supported.

Right click Project that will contain EF Core code.

Select new menu item: Generate renaming files from EDMX.

Get a dialog with a Textbox, Browse button that opens File Open dialog, and OK/Cancel buttons.

Pressing OK calls rulegenerator:

-- check if edmx file exists
-- check if renaming file already exists, and stop if they do

var generator = new RuleGenerator(edmxPath);  
var rules = generator.TryGenerateRules();  
await generator.TrySaveRules(projectBasePath);

@R4ND3LL How do you currently handle multiple DbContexts in the same project?

**Comment by R4ND3LL** [comment]
Just published the NuGet package EdmxRuler v1.0.5

This update has some refactoring (breaking changes), perf improvements, logging support etc.  I feel like the API surface is more stable now.  You should be safe to write code against it (in regards to more breaking changes).

When picking an EDMX in the UI, it might be convenient to also have a drop-down of all the EDMX files found in the solution hierarchy.   Could get a list something like this:
```csharp
    public static Task<string[]> FindEdmxFilesNearProjectAsync(string projectBasePath) {
        return FindEdmxFilesInSolutionAsync(FindSolutionParentPath(projectBasePath));
    }
    public static Task<string[]> FindEdmxFilesInSolutionAsync(string solutionBasePath) {
        return Task.Factory.StartNew(() => Directory.GetFiles(solutionBasePath, "*.edmx", SearchOption.AllDirectories));
    }
    public static string FindSolutionParentPath(string projectBasePath) {
        var di = new DirectoryInfo(projectBasePath);
        while (di != null && di.GetFiles("*.sln", SearchOption.TopDirectoryOnly).Length == 0) {
            di = di.Parent;
        }
        if (di == null || !di.Exists) return projectBasePath;
        return di.FullName;
    }
```

Once generated, you can save the rules using custom names like this:
```csharp
await generator.TrySaveRules(projectBasePath,  
    new RuleFileNameOptions() {  
        PrimitiveNamingFile= null, // null will skip this file 
        NavigationNamingFile = "efpt.navigation-naming.json",   
        PropertyTypeChangingFile = "efpt.property-types.json"  
  }  
);
```
You want to skip the PrimitiveNamingFile because you have your own model for this.  Currently, this model matches yours perfectly.  You will just want to pull the primitiveNamingRules.Schemas collection, and map it over to your file.

The "enum mapping" has been rebranded as Property Type Changing since this file can be used to apply ANY new type name.  This is tested and working fine.  It only requires that the referenced enum exists in the code base somewhere.  i.e. it currently does not generate the enum types (but might later).

There are 2 concerns with multiple DbContexts in 1 proj:
1) For projects with multiple contexts or just a bunch of similarly named entity classes, each rule file has an optional "Namespace" property that is used to ensure that the correct entity is identified (by full name). By default, this is empty because the Reverse Engineered entities often don't match the original EDMX namespace due to subfolder usage etc.
2) If a user wants to apply EDMX rule refactoring to more than one DbContext, then this will come down to the organization of the json files.  i.e. the context name should be stored in the EDMX like "MyDbContext.Navigation-Naming.json".  Since you are saving and loading these manually, then this should be simple.

It would not be a good idea to merge navigation rules for multiple contexts into one json file given that the user requires the ability to regenerate the rules from EDMX at any time if they performed updates on a context.  So separating the json files per context as mentioned is best.

**Comment by R4ND3LL** [comment]
Just published 1.0.6 with much better accuracy in predicting the Reverse Engineered navigation names.

It now emulates the current EF navigation name methods.   

@ErikEJ, I found your implementation of CandidateNamingService in the Power Tools, which you use to apply the primitive property naming.

Rather than using RuleApplicator to apply the navigation naming using Roslyn, I suggest that we override the corresponding methods in the CandidateNamingService and apply the navigation names directly.  This will be better performance-wise and perfect in terms of property identification.  For example, I can include the actual FK name in the json model which can be easily compared against the EF metadata during the naming phase.

While the name guessing works well, the above would be unbeatable.   What do you think?

FYI, the methods to override would be:
```csharp
string GetDependentEndCandidateNavigationPropertyName(IReadOnlyForeignKey foreignKey);
string GetPrincipalEndCandidateNavigationPropertyName(IReadOnlyForeignKey foreignKey,..);
```

**Comment by ErikEJ** [comment]
>> FYI, the methods to override would be:

Yeah, that what was attempted before and failed miserably, it is impossible to predict the end name at that point.

**Comment by ErikEJ** [comment]
What will happen if the user's EDMX model is not on-to-one with the underlying tables?

**Comment by R4ND3LL** [comment]
> > > FYI, the methods to override would be:
> 
> Yeah, that what was attempted before and failed miserably, it is impossible to predict the end name at that point.

I currently have EdmxRuler renaming properties at 99% accuracy for a project with 380+ tables.   I expect that to be 100% with the aid of extra metadata.    "Failure" is safely in the rearview mirror at this point.

> What will happen if the user's EDMX model is not one-to-one with the underlying tables?

Glad you asked.  As the DB model is changed, new elements will end up with their default EF-generated names.  Anything not recognized will be ignored.   So the user will have 2 options if they don't like the names:
1. Modify the JSON rules by hand to add a naming rule for the new element.
2. Update the EDMX from the database, make the name change in the EDMX, and regenerate the rules. (this is what @2xRon plans to do).

This is a good segue into the **Roadmap** for EDMXRuler:
- For long-term development in the database-first approach, I feel this workflow would benefit greatly from a UI Designer that will read the generated EF model, and provide a simple Model Browser with the ability to rename classes and properties.
- Modifications would be persisted to the JSON rule files and applied during the next Reverse Engineer.
- I can design this form, as I already made the equivalent in the past for EDMX model editing, which provided special features like smarter navigation name suggestions.
- This can potentially live in another NuGet package like EntityFramework.UiDesigner.
- This feature would **appeal to ANYBODY who Reverse Engineers the model**, not just those starting with an EDMX file.  
- Once the feature is done, if you were interested, you could use it just by calling EfDesigner.Show(..)
_** Just brainstorming here.  None of this is even started yet_

**Comment by ErikEJ** [comment]
What will happen if the user's EDMX model is not one-to-one with the underlying tables? - I mean if TPH or TPT mapping is used in the EDMX

**Comment by R4ND3LL** [comment]
> What will happen if the user's EDMX model is not one-to-one with the underlying tables? - I mean if TPH or TPT mapping is used in the EDMX

Assuming they use the same strategy on the EF Core side, such that the resulting classes are structured the same as their old model, then it shouldn't matter.  The rules are concerned with "what class has what property"; it doesn't care about the DB.  

I can add some unit testing for this scenario if needed.

**Comment by ErikEJ** [comment]
But EF Core Power Tools is reverse engineering, not domain modelling. But I guess it will just be a limitation of the feature.

**Comment by R4ND3LL** [comment]
Yeah, if there is no way to tell the Reverse Engineer to use inheritance the way it is in the old model, then the user has bigger issues anyway;  They'll have to refactor their code to adapt to the generated EF7 model as-is, or go code-first.

**Comment by R4ND3LL** [comment]
As a progress update, EDMX Ruler has been rebranded as **Entity Framework Ruler**.  A lot has been done in the last week:
1) The [EntityFrameworkRuler CLI](https://www.nuget.org/packages/EntityFrameworkRuler/#readme-body-tab) writes a single rule file with navigations and type mapping built in.  So one rule file has everything.  Proper multi-context support by using context name.
2) Added [EntityFrameworkRuler.Design](https://www.nuget.org/packages/EntityFrameworkRuler.Design/#readme-body-tab), which provides Design Time scaffolding services.  This means rules are applied DURING the scaffold command, very quickly, and effectively.  Using efruler CLI to apply rules (after scaffolding) using Roslyn is still available if needed.
3) Entity configuration splitting feature available if enabled in the rule file. 
4) Various options added to rules such as the exclusion of unmapped tables/columns etc. 
3) Too many other enhancements and fixes to name.

So now the primary workflow is much simpler:
1) Generate rules from EDMX using [efruler CLI](https://www.nuget.org/packages/EntityFrameworkRuler/#readme-body-tab) with rule file placed in EF Core project.
2) Reference [EntityFrameworkRuler.Design](https://www.nuget.org/packages/EntityFrameworkRuler.Design/#readme-body-tab) from the EF Core project.
3) Run "dotnet ef dbcontext scaffold .." command and like magic, you get a model that's identical to the EF6 EDMX version.

@2xRon, do you think you can give the current version (>= 1.0.27) a try for your workflow and provide feedback?  

I have it working well on 2 of my projects currently.

**Comment by ErikEJ** [comment]
I will add this link https://www.nuget.org/packages/EntityFrameworkRuler.Design/#readme-body-tab to the wiki for the time being

**Comment by R4ND3LL** [comment]
@ErikEJ, EntityFrameworkRuler can still be integrated into Power Tools quite easily if interested.  From a high level, it will give you:
1) Fast and reliable custom naming of navigations, in addition to what you currently support with classes, properties, etc.  
2) Generation of the naming json file from EDMX.
3) Coming soon: generation of the naming file from the scaffolded DBContext, such that users that are NOT upgrading from EDMX can initialize the file, make customizations, and maintain their custom naming on subsequent reverse engineers.
3) Coming soon: visual editor for the json file, allowing users to easily customize the content and options.

Rather than the Roslyn approach originally planned, you would reference [Design](https://www.nuget.org/packages/EntityFrameworkRuler.Design/#readme-body-tab) and use the [RuledCandidateNamingService](https://github.com/R4ND3LL/EntityFrameworkRuler/blob/main/src/EntityFrameworkRuler.Design/Services/RuledCandidateNamingService.cs) either from, or as a replacement to, your ReplacingCandidateNamingService.

As for the UI components mentioned above, I have started a NuGet package where I will implement the dialogs so that they can be simply referenced and used from Power Tools.

This approach minimizes the amount of code in your project related to this feature,  so it should be easier for you to maintain and update as needed.  

This is all up to you.  Right now my workflow is usable from CLI so I'm happy.  As for the UI components, I'll figure something out eventually if you decide not to integrate.  

I appreciate your help and input thus far, by the way.  Thanks.
