### ISSUE TITLE
Reverse engineering - The generated database context is incorrect

### ISSUE THREAD

**Issue by TanguyPa** [ErikEJ/EFCorePowerTools#1611]
When generating a configuration with only stored procedures (in this case I selected only one procedure) and using a different path for the DbContext and EntityTypes.
The generation of the MyDbContext adds the instruction 
```csharp
 using MyProject.Data.MyDb.Models;
```

I configure my eftp.config.json file for each database as follows.
![image](https://user-images.githubusercontent.com/44705035/206226222-98d86640-7832-4386-9d0c-f6b4066f2bcf.png)

The problem is that in this case I have no EntityTypes generated, so the file containing the db context is invalid since no file uses the namespace MyProject.Data.MyDb.Models.

The using statement of the EntityTypes namespace should be added only if at least one of the EntityType is generated with the namespace.

I think this is a pretty rare case, in my case I have configured the EntityTypes namespace in advance to anticipate when I will have EntityTypes created via views or tables but for now I only have procedures.

- EF Core version in use: EF Core 6

- Is Handlebars used: no

- Is T4 used: no

- Is .dacpac used: no

- EF Core Power Tools version: 2.5.1206

- Database engine: SQL Server

- Visual Studio version:  Visual Studio 2022

**Comment by ErikEJ** [comment]
Nnik

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Tanguy Pauze ***@***.***>
Sent: Wednesday, December 7, 2022 5:14:05 PM
To: ErikEJ/EFCorePowerTools ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ErikEJ/EFCorePowerTools] Reverse engineering - Namespace problem when using only storred procedure (Issue #1611)


When generating a configuration with only stored procedures (in this case I selected only one procedure) and using a different path for the DbContext and EntityTypes.
The generation of the MyDbContext adds the instruction

 using MyProject.Data.MyDb.Models;

I configure my eftp.config.json file for each database as follows.
[image]<https://user-images.githubusercontent.com/44705035/206226222-98d86640-7832-4386-9d0c-f6b4066f2bcf.png>

The problem is that in this case I have no EntityTypes generated, so the file containing the db context is invalid since no file uses the namespace MyProject.Data.MyDb.Models.

The using statement of the EntityTypes namespace should be added only if at least one of the EntityType is generated with the namespace.

Je pense que c'est un cas assez rare, dans mon cas j'ai configuré le namespace des EntityTypes en amont pour prévoir lorsque j'aurais des EntityTypes créés via des vues ou tables mais pour l'instant j'ai uniquement des précodures.

  *   EF Core version in use: EF Core 6

  *   Is Handlebars used: no

  *   Is T4 used: no

  *   Is .dacpac used: no

  *   EF Core Power Tools version: 2.5.1206

  *   Database engine: SQL Server

  *   Visual Studio version: Visual Studio 2022
