### ISSUE TITLE
Reverse engineering option issue

### ISSUE THREAD

**Issue by Artlake** [ErikEJ/EFCorePowerTools#1705]
Im having an issue where i want to include 'many to many/bridge' table in reverse engineering process, but that table is not included in my models folder as an entity. I think there is an issue when i have constraint for two primary keys in one table. Issue is present in both EF Core 6 and 7 selected. Table is visible for selection when user is prompted to select tables.

Options used for reverse engineering:
EntityTypes path(f.ex. Models) - optional = Models
DbContext path (f.ex Data) - optional = Context
What to generate = EntityTypes only
Naming (both options are checked) 
In advanced window:
Use schema folder separation (experimental = true

Using SQL Server, Visual Studio 2022. 

SQL code for tables:
CREATE TABLE films (
  film_id INT PRIMARY KEY
 ,title VARCHAR(50)
 ,director VARCHAR(50)
 ,year_released DATETIME
);
CREATE TABLE category (
  category_id INT PRIMARY KEY
 ,name VARCHAR(50)
);
CREATE TABLE film_category ( --< table that is not present in project after reverse engineering process is done
  film_id INT
 ,category_id INT
 ,CONSTRAINT film_cat_pk PRIMARY KEY (film_id, category_id)
 ,CONSTRAINT FK_film
  FOREIGN KEY (film_id) REFERENCES films (film_id)
 ,CONSTRAINT FK_category
  FOREIGN KEY (category_id) REFERENCES category (category_id)
);

Thanks in advance.

**Comment by ErikEJ** [comment]
By design simple many-to-many tables are no longer scaffolded with EF Core 6. You do not need them.

There is a option to bring them back in advanced options.

If you like my free tools, I would be very grateful for a rating or review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details) or even a [one-time or monthly sponsorship](https://github.com/sponsors/ErikEJ?frequency=one-time&sponsor=ErikEJ)

**Comment by Artlake** [comment]
Thanks Erik, i missed this option. It works with that one checked. I have rated your tool.
