### ISSUE TITLE
Take custom path into consideration when dropping t4 templates

### ISSUE THREAD

**Issue by ErikEJ** [ErikEJ/EFCorePowerTools#1875]

**Comment by ErikEJ** [comment]
@ClaudioBiagioli FYI

**Comment by ErikEJ** [comment]
@ClaudioBiagioli Did you have a chance to test this?

**Comment by ClaudioBiagioli** [comment]
Hi @ErikEJ, 
it works quite well if I set an absolute Path.
If instead I set a relative one (like ..\\..) the CodeTemplates folder is created in the root, so it's to undestand where the relative path starts from: it should be from the project root folder in my opinion.
A relative path is much more suitable because the developers may use different paths for their Git main folder.

Thanks
CB

**Comment by ErikEJ** [comment]
@ClaudioBiagioli Cool, thanks for confirming. I have created https://github.com/ErikEJ/EFCorePowerTools/issues/1876

It will be relative to the current project root folder when implemented, yes.

If you like my free tools, I would be very grateful for a rating or review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details) or even a [one-time or monthly sponsorship](https://github.com/sponsors/ErikEJ?frequency=one-time&sponsor=ErikEJ)
