### ISSUE TITLE
Add support for Firebird

### ISSUE THREAD

**Issue by ErikEJ** [ErikEJ/EFCorePowerTools#195]
Need Simple DDEX provider + ADO.NET client

**Comment by ErikEJ** [comment]
No DDEX provider for 2017 :-(

**Comment by MagicAndre1981** [comment]
yeah, long requested, but not delivered. An user tried to [implement it in his fork](https://github.com/danielrail/NETProvider/tree/NetProvider_VSIX) but no longer has time to finish it.

**Comment by ErikEJ** [comment]
@MagicAndre1981 The DDEX provider can be very simple for use with Power Tools, simply require the capability to persist connections in "Server Explorer"

**Comment by MagicAndre1981** [comment]
current DDEX provider can also do this, but because of MSI installer, the registration of the Firebird DDEX provider is lost after updating a VSIX so we need to import the reg with the data again and this is complicated since VS2017 and the private registry hive file. This is why I also want a VSIX based provider

**Comment by ErikEJ** [comment]
For required changes for a new provider, see https://github.com/ErikEJ/EFCorePowerTools/pull/182

**Comment by ErikEJ** [comment]
Duplicate of #288

**Comment by ErikEJ** [comment]
@MagicAndre1981 Enabled in latest daily build!
