### ISSUE TITLE
Rev eng re-architect for EF Core 3.0

### ISSUE THREAD

**Issue by ErikEJ** [ErikEJ/EFCorePowerTools#196]
Rework as a .NET Core command line tool, initially just pass json payload with settings, and initially only support SQL Server.

- [x] Add shared .NET Standard 2.0 library (with pathhelper, reverseengineeroptions, interface for RevEng20 class etc.)
- [x] Create new project, .NET Core 3.0 Console app, use shared lib
- [x] Update UI: Checkbox for EF Core 3.0, get views from table queries, do not disable selection of views
- [x] Get views in scripting lib
- [x] Verify UI with actual views
- [x] Add method in current RevEng20 class that unzips and launches the .NET Core app, and gets results back.
- [x] Testing!
- [x] Disable includeViews for not implemented providers (MySQL, SQL CE)

 

Later publish as dotnet global tool ?

**Comment by JonPSmith** [comment]
Hi @ErikEJ. Yep that would help, mainly because of the `OnModelCreatingPartial`, but I have a solution that works for my client. If EF Core 3 adds your  `OnModelCreatingPartial` I will be happy with that.

BTW: It would be nice to be able to add specific puralization overrides to your tool. I noticed it puralized "Photo" to "Photoes". I has to add a Design Time puraliziser to my system and the first one puralized "Process" to "Proces" so I changed the puraliziser package and now "Process" becomes "Processes".

PS. I used your tool while developing but my client wanted  a script.

**Comment by ErikEJ** [comment]
My tool supports custom renaming.

**Comment by JonPSmith** [comment]
Great about custom renaming. Could you give me a link to the documentation on that.

**Comment by ErikEJ** [comment]
Hmmm... Let me create a wiki post!!

**Comment by ErikEJ** [comment]
Wiki post here: https://github.com/ErikEJ/EFCorePowerTools/wiki/Reverse-Engineering#custom-renaming-with-epftrenamingjson

**Comment by JonPSmith** [comment]
Thanks. I looked back through your code to `ReplacingCandidateNamingService` to get a better idea of what is happening underneath.
