### ISSUE TITLE
Make VS extension read efcpt-config.json

### ISSUE THREAD

**Issue by ErikEJ** [ErikEJ/EFCorePowerTools#2102]
If there is a efcpt-config.json file in the project folders, and no efpt*.config.json files, read options from the efcpt-config.json file.

**Comment by ErikEJ** [comment]
(This could be confusing as not all VS features hav been implemented in the CLI)

**Comment by jwyza-pi** [comment]
Yeah, I probably won't be able to work on this due to the size of it, but I did notice that, for example, the "ExcludedColumns" property of the tables isn't in the CLI.  Kind of seems like really the CLI would need to have feature parity as far as scaffolding/generation goes before this would make sense. Otherwise trying to map between them could be kind of difficult for users to grok why it behaves differently.

**Comment by tstephansen** [comment]
I'm just adding my 2¢ (I'm not familiar enough with this code base to actually implement it myself). This would be very useful to me. I work in both a Windows and Mac environment. I have a custom tool I made to create the migrations but I currently have to use windows to scaffold the dbcontext. If we could pass this config file to the CLI and have it scaffold the context the same was as on windows it would save me the headache of having to go between computers. I understand if this isn't feasible at this time.

**Comment by ErikEJ** [comment]
@jwyza-pi I am not planning to do this.

**Comment by ErikEJ** [comment]
@tstephansen @jwyza-pi I was thinking about this. 

How about the ability to only read from efpt-config.json in the VS extension (now that most features are available in the CLI) - writing should still happen manually or by running the CLI.

**Comment by ErikEJ** [comment]
@tstephansen @jwyza-pi Any interest?

**Comment by tstephansen** [comment]
> @tstephansen @jwyza-pi Any interest?

Sorry for the delay in my response. Yes, thank you. That would work perfectly.
