### ISSUE TITLE
Reverse Engineer - Rename navigation and reference properties

### ISSUE THREAD

**Issue by WalterAtTally** [ErikEJ/EFCorePowerTools#211]
Is it possible to rename the generated navigation properties?

### Steps to reproduce
Say there are two tables,

CREATE TABLE Product (
Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY, 
CategoryCode VARCHAR(20) FOREIGN KEY (CategoryCode) REFERENCES Category (Code) NULL, 
ParentId UNIQUEIDENTIFIER FOREIGN KEY (ParentId) REFERENCES Product (Id) NULL
)

CREATE TABLE Category (
Code VARCHAR(20) NOT NULL PRIMARY KEY,
Description VARCHAR(100) NOT NULL
)

Product table references both Category and Product itself. The generated class contains the following navigation properties, which I very much want to rename to something more meaningful.

`public Category CategoryCodeNavigation { get; set; }`
`public Product ParentProduct {get;set;}`
`public virtual ICollection<Product> InverseProduct {get; set;}`

I have tried to use efpt.renaming.json, but it only supports renaming columns not FK relations.

I understand I can just manually rename the properties after the code-gen, but the changes will be overwritten when the project is re-generated which we do quite often.

So is there a workaround to rename FK navigation properties?

Thanks for any tips!

### Further technical details
EF Core Power Tools version: (found in About dialog - blue questionmark icon on context menu)
2.2.12.0

Database engine: (SQlite, SQL Compact, SQL Server, Postgres)
Azure SQL

Visual Studio version: (e.g. Visual Studio 2017 15.7)
VS2019

**Comment by ErikEJ** [comment]
I think it is not possible

**Comment by german95n** [comment]
Not even with Handlebars?

**Comment by ErikEJ** [comment]
Feel free to give it a try

**Comment by jamshally** [comment]
+1 for this feature request. @ErikEJ - from your understanding, is this still not technically possible? It's been a year now, so I figured it was worth asking - even if a long shot. I'd be happy to have a go at contributing an update if there was a workable solution - would just need a few pointers to get going.

Thanks for this great tool. It is immensely helpful.

**Comment by ErikEJ** [comment]
@jamshally  Let's have a look - please explain (with some sample code) what you see now, and what you would like to see instead.

**Comment by jamshally** [comment]
@ErikEJ - OK, here is my scenario:

I have a table with a two column foreign key. The Auto-name-generation of Navigation Property seems to look for common characters between the foreign key fields, sometimes resulting in unsuitable field names. I am looking for a way to rename these Navigation properties during a reverse-engineering code-generation cycle. Example code below:

### Tables
![image](https://user-images.githubusercontent.com/39815557/93647342-20798400-fa00-11ea-8b48-7d477bce918d.png)

### Table SQL
``` SQL
CREATE TABLE [dbo].[Product](
	[V1ProductId] [nchar](10) NOT NULL,
	[V1Index] [nchar](10) NOT NULL,
	[Data] [nchar](10) NULL,
CONSTRAINT [PK_Product] PRIMARY KEY CLUSTERED ([V1ProductId] ASC,	[V1Index] ASC) ON [PRIMARY]

CREATE TABLE [dbo].[ProductMetaData](
	[V1ProductId] [nchar](10) NOT NULL,
	[V1Index] [nchar](10) NOT NULL,
	[MetaData] [varchar](50) NULL,
 CONSTRAINT [PK_ProductMetaData] PRIMARY KEY CLUSTERED ([V1ProductId] ASC, [V1Index] ASC) ON [PRIMARY]

ALTER TABLE [dbo].[ProductMetaData]  WITH CHECK ADD  CONSTRAINT [FK_ProductMetaData_Product] FOREIGN KEY([V1ProductId], [V1Index])
REFERENCES [dbo].[Product] ([V1ProductId], [V1Index])
````

### Generated Model Class
``` C#
    public partial class ProductMetaDatum
    {
        public string V1productId { get; set; }
        public string V1index { get; set; }
        public string MetaData { get; set; }

        public virtual Product V1 { get; set; } //<------ Would like to rename this field
    }
```

**Comment by ErikEJ** [comment]
What custom name?

**Comment by jamshally** [comment]
> What custom name?
@ErikEJ - I have several similar scenarios in a database I am working with. In this instance I'd like to name the Navigation Property "Product"

**Comment by ErikEJ** [comment]
@jamshally  Have you tried the renaming feature  ?- with this efpt.renaming.json file, for example:

[
  {
    "UseSchemaName": false,
    "SchemaName": "dbo",
    "Tables": [
      {
        "Name": "ProductMetaData",
        "Columns": [
          {
            "Name": "FactoryId",
            "NewName": "ProductId"
          }
        ]
      }
    ]
  }
]

**Comment by jamshally** [comment]
Hi @ErikEJ , thanks for the suggestion.

This does result in the Navigation Property being generated with the name "Property", but then the name of the FactoryId is no longer correct/consistent with the business domain. The primary key of the Product _is the combination_ of the FactoryId and the FactoryProductIndex. 

Basically, the naming of the primary key fields are as-intended, it is just the auto-generated naming of the Navigation Property I would like to change.

**Comment by ErikEJ** [comment]
Not something I plan to implement

**Comment by kinetiq** [comment]
Just coming to EF Core Power Tools, and it seems like this is should be an obvious problem. Every time I re-generate, I have to re-name several fields because they have bizarre names, to the extent that I'm the only one on my team who is allowed to re-generate... Bummed to discover there's no remedy and it isn't being considered.

Is this something you would accept a pull request on, if I could figure out how to get it done?

**Comment by ErikEJ** [comment]
@kinetiq sure, a PR that does not pull in huge amounts of EF Core code to do this would be appreciated.

**Comment by kinetiq** [comment]
@ErikEJ Thanks, I will see what I can do. :)

**Comment by ErikEJ** [comment]
@kinetiq great, let me know if I can help in any way.

**Comment by kinetiq** [comment]
@ErikEJ   So I found what seem to be the key components, maybe you could confirm that I'm on the right track.

I'm also going to call on the other folks who care about this to pitch in and see if you can help solve this. There is plenty for everyone.

-  **ReverseEngineer20.ReverseEngineer.ReplacingCandidateNamingService** seems to be where the magic happens. Not a lot of comments to be found, but it seems this whole class is about overriding internal APIs to customize the reverse engineering process. GenerateCandidateIdentifier for instance looks like it might be specific to generating names for tables, and that isn't what I need (or is it?), but I can see a pattern for using the Schema class to customize things. @ErikEJ  could you confirm that I'm in the right place, and that this is the only place I need to care about for this? The fact that the namespace is numbered worries me.
- This lead me to **Schema**  and the List<Schema> on ReplacingCandidateNamingService. I initially wondered why a List<Schema> was required since Schema contains a list of table details, but then I realized it covers cases where a database goes beyond dbo and has multiple schema names. No problem. I also found some tests that were helpful. I could use some help understanding how to extend this.
- Back to ReplacingCandidateNamingService, I see GetDependentEndCandidateNavigationPropertyName and it seems important. I see that it takes IForeignKey as a parameter and you are doing something custom with it. What is this? I did some googling and found no clues.
- Well actually, I found out that GetPrincipalEndCandidateNavigationPropertyName  also exists and can be overridden. Source for both is here: https://github.com/dotnet/efcore/blob/main/src/EFCore.Design/Scaffolding/Internal/CandidateNamingService.cs ...  This appears to handle a lot of scary-looking edge cases without a single comment. The lack of comments is quite discouraging.
 - I would imagine that GetDependentEndCandidateNavigationPropertyName and GetPrincipalEndCandidateNavigationPropertyName  might handle the two sides of the navigation property... Can anyone confirm how these fit together? Both of them take IForeignKey which seems strange; for my theory to be correct, one of them would probably be a primary key. 

So this is turning into a lot. Any help would be appreciated.

**Comment by kinetiq** [comment]
Not detecting a lot of passion on this. :)

**Comment by kinetiq** [comment]
Loud and clear, this is not something anyone cares to help with. Might as well close this one, I am tapping out.

**Comment by ErikEJ** [comment]
There are a lot of complexities involved here, like how do you specify the revised naming rules, that need to be sorted out before actually implementation of any renaming mechanics

**Comment by ErikEJ** [comment]
I wonder if the ability to rename tables and columns solves this issue?

**Comment by kinetiq** [comment]
> There are a lot of complexities involved here, like how do you specify the revised naming rules, that need to be sorted out before actually implementation of any renaming mechanics

True, but that is relatively straightforward compared to the technical part. My intention was to set this up so that it does whatever it normally does, but defers to some new items in the configuration file. 

> I wonder if the ability to rename tables and columns solves this issue?

Based on the 9/22 response from @jamshally, it seemed like this was not direct enough. Although I should probably test it for my own purposes.

**Comment by ErikEJ** [comment]
Could you outline what the configuration entries could look like?

**Comment by kinetiq** [comment]
@ErikEJ I haven't gotten that far, I am still in the "is this even possible and where would the code go" phase. 

Maybe under Tables > Columns there could be a setting specifically for naming navigation properties.

**Comment by ErikEJ** [comment]
The current experimental implementation is causing too much confusion and is broken.

I will remove and re-think.

**Comment by kinetiq** [comment]
Yes, really hoping you get this working at some point. Seems like in the experimental version, I was able to get it to work but there were cases that it just didn't cover.

**Comment by ErikEJ** [comment]
>>but there were cases that it just didn't cover.

@kinetiq Exactly, and I did not want that support burden of a broken feature.

The previous attempt: https://github.com/ErikEJ/EFCorePowerTools/commit/f9e962d6607bca53e3787aa985a73028644a16a0

**Comment by OculiViridi** [comment]
@ErikEJ Wouldn't it be possible, to just use the "plural naming convention" on the auto generated navigation properties?

Please see the sample code below:

```csharp
public partial class Order
{
	public long OrderId { get; set; }
	public long CustomerId { get; set; } 

	public Customer Customer { get; set; }
	
	public virtual List<OrderItem> OrderItems { get; set; } // <-- Plural naming convention
	// or public virtual IEnumerable<OrderItem> OrderItems { get; set; }
	// or public virtual ICollection<OrderItem> OrderItems { get; set; }
	// ...
}

public partial class OrderItem
{
	public long ItemId { get; set; }
	public string Description { get; set; }	
	// ...
}
```

**Comment by ErikEJ** [comment]
The hook that is currently there is too early in the naming pipeline

**Comment by viktorszekeress** [comment]
Might be just very nainve suggestion, but wouldn't refactor/rename do the trick? I mean that's what I'm actually doing after running the tool.

**Comment by ErikEJ** [comment]
@viktorszekeress the code generation is not compiled code...

**Comment by viktorszekeress** [comment]
You don't need compiled code to run refactor/rename in VS, do you?

**Comment by ErikEJ** [comment]
@viktorszekeress l think you do to some extent...
Feel free to submit a PR...

**Comment by viktorszekeress** [comment]
I'm using Resharper rename function and I'm pretty sure it does the job even if code isn't compiled yet. Haven't tested all the edge cases, though.
Anyway, can the tool run compilation and then do rename? I'm doing this manually right now, so all I need is to make this process automatized and to follow the mappings from config.json.

I would love to submit a PR if I had any idea how extensions in VS work.

**Comment by CaiusJard** [comment]
I think that EF team/EEJ probably intended for "Reverse Engineer" (or scaffold-dbcontext as we call it from command line) wasn't intended to be used repeatedly; You use it once, you customize the output, and then you use migrations every time you want to make changes.. (Or you use it repeatedly but you accept the limits of the customizations you can make)

Now.. I know that generally adding things to a DB by adding properties to entites and reams of code to the context and then saying "migration.. go!" and having the system work out how your old context and your nhew context changed and generate SQL to make the same thing in a DB is something you want to stay away from - it makes me want to stick pins in my eyes too compared to the nice graphical way of "design table, add column, create relationship by drag and drop, done"..

So I tend to:

a) have a test/dev db that is well synced, schematically, with live
b) make changes to dev graphically
c) use EFCPT or command line to scaff my new dev db into a *different* folder to what my modified context is in.. e.g. the true context my project uses is in `Contexts\` and I have EFCPT put the new one in `Contexts\New\`
d) use a diff tool to copy across the changes I want from the New\*.cs files into my existing context (plug for BeyondCompare; I don't think there is a better diff tool out there)
e) use EFCPT to add a migration that will modify the live DB when i finally put it live
f) copy the `20200101123456_MyMigrationName` out of the migration filename and paste it into the `__EFMigrationsHistory` table in dev, to make EFCPT think the migration is already applied (it is, in dev.. it was done graphically and then changes scaff'd from it so trying to apply it again will give e.g. "table already exists")
g) delete the entire `New\` folder and all its duplicate code that is causing thousands of build errors (or you could gen to a folder outside your project root)

Yes, it's a bit of a pain.. but you have to remember that the scaff'd context files are autogenerated - nearly every autogen'd file i've come across has a comment at the top like "this is autogenerated; changes will be lost if regenerated.." as a "don't edit this..". 

If you want to use the autogenerate process to help out but then want to pick and choose the changes (and there isn't a way to pick and choose automatically/make the changes as part of the autogen; there is sometimes, like getting EFCPT to not scaff a particular thing and then wiring that up yourself in the partial) youre probably looking at a process of manually cherry picking the bits you want..

**Comment by CaiusJard** [comment]
All that said, don't forget that you don't have to be too sophisticated with any tooling to help yourself out - knocking together a small command line app that runs through every file in a directory and carries out a set of find/replace is very easy to do.. It doesn't have to touch your main code, because EFCPT will only have generated `public string SomeColumn {get;set;}` and if you want that as `[Column(TypeName = "varchar(50)")]public MyEnum SomeColumn { get; private set; }` then it's a quick string replace on just the XYZ.cs file - until it's done your project has a build error every time it says XYZ.SomeColumn as if it were an enum (but it generates as a string) but the good thing is that the entity cs file gneerates consistently, so it'll respond well to simple find replace (like `File.WriteAllText("path to entity", File.ReadAllText("path to entity").Replace("a","b")) in a console app` run as part of the build..

**Comment by kinetiq** [comment]
@CaiusJard There are features built in that allow name changes at the time of generation, and this thread is about improving them so they work in a few additional cases.

**Comment by jerran** [comment]
I'd also like to see this feature implemented, but in the meanwhile, here's my workaround to it.

Make aliases for the awkwardly named navigation properties in separate partial class files, which don't get overwritten by auto-generation.

In my example case I have a tree structure of categories stored in the database as:
```
CREATE TABLE [dbo].[Category]
(
[CategoryId] INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
...
[ParentCategoryId] INT NULL,
CONSTRAINT [FK_Category_Category] FOREIGN KEY ([ParentCategoryId]) REFERENCES [Category]([CategoryId])
)
```

The Navigation property gets generated as _InverseParentCategory_, which I'd rather call _ChildCategories_ instead:
```
namespace MyApp.Models
{
	[Table("Category")]
	public partial class Category
	{
		...
		[InverseProperty(nameof(Category.ParentCategory))]
		public virtual ICollection<Category> InverseParentCategory { get; set; }
		...
	}
}
```

So I made a project folder called `ModelAliases` and added a `CategoryAliases.cs` file. I added a property with the name I wanted to use and mapped the accessors to the original property I wanted to alias. The `[NotMapped]` attribute from `System.ComponentModel.DataAnnotations.Schema` is needed, or else the auto-generated DbContext will throw an error when you try to access `Category` objects in the database.
```
using System.ComponentModel.DataAnnotations.Schema;
namespace MyApp.Models
{
	public partial class Category
	{
		[NotMapped]
		public virtual ICollection<Category> ChildCategories
		{
			get { return InverseParentCategory; }
			set { InverseParentCategory = value; }
		}
	}
}
```

The downside is of course, that the auto-generated names will still remain a part of the class as well. Whether you can live with that or not, may depend on your specific circumstance.

Maybe this aliasing approach is also something that could be integrated into EF Core Power Tools with less effort than the actual property renaming seems to require?

**Comment by pcrbziss** [comment]
The experimental implementation of renaming navigation properties @ErikEJ had up earlier this year wasn't perfect, but it was pretty good and worked for most of my  data. When it got pulled out, I wound up writing  a bunch of code that looks like the partial class code @jerran has above, but am not thrilled with the solution.

**Comment by RaulFunezp** [comment]
@jerran.  Thank you very much for your sample. Although not the perfect solution but good enough to allow me to move forward in migrating my projects from EF6 EDMX to EF Core 6.

**Comment by CorsairRO** [comment]
Hello all.

I dont like either the naming stuff for navigations. 
Unfortunately i dont think it is Erik's code that does anything, he just calls the EF Core Scaffolder and he gets back the result and put into classes.

The solution i am using now ( because i have lots of legacy names for tables and they look really UGLY for navigation properties ) is that i use the NO NAVIGATIONs option.
Then i go to OnModelCreating and add them accordingly with my names to Nav Prop.

Also i get rid of unwanted behaviors there with loading shit loads of relations when i dont need them. Like having a context for lookups only where i dont want it ato have any relations at all

**Comment by kinetiq** [comment]
@CorsairRO Wouldn't you need to manually create each navigation property if you did that?

**Comment by CorsairRO** [comment]
@kinetiq Yes, i go there and add my Properties named EXACTLY as i want, and add in OnModelConfiguring the relations with .HasOne , .WithMany and so on.

I have many projects with 500+ DB Objects and even with 1000+ and plenty of contexts because i cannot use the single context approach as i will wait 3 minutes for initial warmup of context.
And i have NO PROBLEM doing that as long as it works fine, and Erik'tool just helps me to map the objects and generate them as i wish. For that part Erik's tool helped me with inspiration to make a stripped version of his tool and customized the CSharp Code Generator to do Exactly as i do today with .tt templates. 
Because i work only in desktop ( WPF ) and Xamarin i make all my objects to be Observable and all Collections to be Observable Collections.

Handlebars are unusable for me if i cannot control how i generate my code in deep. Erik's tool doesnt support custom handlers from handlebars and probably will not support it as i looked there by myself and it is hard to implement.

When EF7 will be released (planned autumn) and put back the .tt templating stuff ( currently in progress at MS ) and when Erik will add support for that in the tool, i will kill my version and just use current one.
Adding .tt for objects / context will most probably end the life of Handlebars usage in EF Core code generation.
I wonder which kind of idiot at MS decided to remove the .tt that are working since ~2005 and had NO ISSUE whatsoever with them. edmx from EF on .NET Framework didnt mean that we want diagrams and stuff, just that we want to use templating to generate our objects.

Anyway, thank you very much to ErikEJ for the very nice tool. And i will try to help him as much as i can to fix stuff / add new stuff and so on ...

**Comment by RaulFunezp** [comment]
@Corsair Thank you very much for your comments, they are very helpful for me because I have a similar situation to yours.

**Comment by flencinas** [comment]
EXACTLY I AGREE with YOU

 **wonder which kind of idiot at MS decided to remove the .tt that are working since ~2005 and had NO ISSUE whatsoever with them. edmx from EF on .NET Framework didnt mean that we want diagrams and stuff, just that we want to use templating to generate our objects.


Claps claps... for that Idiot!!!!

**Comment by ErikEJ** [comment]
@flencinas please keep a civilized language.

Support for .tt files is coming in EF Core 7.

**Comment by flencinas** [comment]
I'm sorry Erik 

but for those of us who are part of .Net there are decisions that are made that are totally absurd and that destroy all the power that other great developers give us

I'm sorry again

**Comment by R4ND3LL** [comment]
I have a solution for this that uses Roslyn to rename navigation properties (and references).  Does not rely on compiled code (Roslyn parses code syntax directly).   

It reads rename rules from a new json doc "efpt.renaming-nav.json" (has to be separate from the main one because Power Tools kills rename entries that it can't resolve).   As such, I believe it inherently avoids the above concerns.

I also made a process that generates the rename rules from an existing EDMX.  
Any interest in this?   Ideally it should be incorporated into Power Tools so that these functions can be run via the UI.

**Comment by kinetiq** [comment]
@R4ND3LL Oh I am very interested.

**Comment by ErikEJ** [comment]
@R4ND3LL please submit a drift PR!

**Comment by ErikEJ** [comment]
For anyone following this, an experimental implementation of this is now in the latest daily build. 

It uses a seperate renaming file: efpt.refrenaming.json currently with same format as efpt.renaming.json (this will likely change)

**Comment by ErikEJ** [comment]
Another attempt at this is now in preview, more confidence this time (using Roslyn for consisten renaming) - https://github.com/ErikEJ/EFCorePowerTools/wiki/Reverse-Engineering#custom-renaming-with-efptproperty-renamingjson
