### ISSUE TITLE
Extension debugging

### ISSUE THREAD

**Issue by andresrsanchez** [ErikEJ/EFCorePowerTools#24]
Hello!
On the extension debugging, when I hit F5 in 'EFCorePowerTools' project, in the opened VS (experimental instance) I cannot find the extension dialog right clicking a project like the wiki says (netstandard type). How I can debug the extension?

![image](https://user-images.githubusercontent.com/34173061/40472919-1784e040-5f3b-11e8-9c97-0c49388aebce.png)

Thanks for all and sorry for my English.

**Comment by ErikEJ** [comment]
# Building and debugging

In order to build the source code, use Visual Studio 2017 - run as Administrator. You will also need the SQL Server Compact 3.5 SP2 and 4.0 runtimes installed. To debug, make VSToolbox the startup project, and ensure your build configuration is Debug, x86 (not AnyCPU).

(I have added this to the readme.md file)
