### ISSUE TITLE
Mark file with <auto-generated> message

### ISSUE THREAD

**Issue by herianp** [ErikEJ/EFCorePowerTools#2504]
Hi, is it possible to choose option to mark file with auto-generated message ? If so, how please? In previous version the message was generated by default i guess. (But now, the power tool did not generate it.)

![efcore](https://github.com/user-attachments/assets/c5ea13e8-31c3-4eca-9429-6bb722226197)

### Provide technical details

- EF Core Power Tools version: 2.6.437

- Exact Visual Studio version: 17.8.3

- Database engine: SQL Server

- EF Core version in use: EF Core 8

- Is Handlebars templates used: yes

- Is T4 templates used: no

- Is a SQL Server .dacpac used: i doesnt think so

**Comment by ErikEJ** [comment]
It is because you use Handlebars - why do you need to.

**Comment by herianp** [comment]
Thanks, I will add it to handlebars. Maybe i don't even need it..

**Comment by cn-byn** [comment]
@ErikEJ I don't understand how using T4 is a solution for this issue. The T4 templates bundled with EF Core Power Tools don't seem to include the two lines (neither <auto-generated> or #nullable).

I don't see those lines using the CLI either.

Only the sample T4 files do contain the lines, but they aren't deployed with the installation.
https://github.com/ErikEJ/EFCorePowerTools/blob/master/samples/CodeTemplates/EFCore/EntityType.t4#L190

Or am I missing something?

**Comment by ErikEJ** [comment]
@cn-byn You own the t4 templates and can add anything to them. The sample shows you how. (It is a "sample")

**Comment by HansBM** [comment]
@ErikEJ When I use EFPT without t4, it adds

// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

but when I add T4 with "Add T4 Scaffolding Template" it will no longer output <auto-generated>. This is EF Core Power Tools 2.6.750. 

I am mostly wondering because of this in the documentation:
"If you are adding or removing tables, leave any additional tables selected on subsequent runs of the tool, or all unused files will be removed. If you explicitly want to keep unselected files, **remove the first line with the "autogenerated" comment from each (or rename the file)**."
In https://github.com/ErikEJ/EFCorePowerTools/wiki/Reverse-Engineering#saving-options-and-running-the-second-time

Is this not true, is the line with autogenerated comment not needed for this to work?

**Comment by ErikEJ** [comment]
@HansBM 

 If you like my free tools, I would be very grateful for a rating/review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details) and/or a [one-time or monthly sponsorship](https://github.com/sponsors/ErikEJ?frequency=one-time&sponsor=ErikEJ)
