### ISSUE TITLE
With ORACLE v.19c reverse engineer return error ORA-28040: The database does not accept your client's authentication protocol; login denied.

### ISSUE THREAD

**Issue by davidec** [ErikEJ/EFCorePowerTools#2553]
Hi,
I try to reverse engineer a oracle db v.19c  with ODP.net drive,  the connection test returns success but when I go to the next step I get this error:

 ORA-28040: The database does not accept your client's authentication protocol; login denied.

Version EF Core Power Tools: 2.6.497
Microsoft Visual Studio Professional 2022 (64-bit) - Version 17.9.6
Database : Oracle Database 19c Standard Edition 2 Release 19.0.0.0.0  
EF Core 8

**Comment by ErikEJ** [comment]
This seems to be an Oracle authentication issue - I do not know enough about Oracle to help - suggest you ask Oracle support @alexkeh ?

**Comment by alexkeh** [comment]
@ErikEJ What does the connection test do differently compared to going to the next screen?

@davidec If you initiate an ODP.NET connection from this machine outside EF Core Power Tools, such as using Oracle Developer Tools, are you able to connect or do you experience the same error? What client authentication protocol are you attempting to connect with (i.e., Kerberos, Radius, TLS/SSL, Oracle Native Network Encryption, etc.) ?

**Comment by davidec** [comment]
HI,

If I create a connection outside of EF POWER TOOL it works. Test connection OK and lists the tables and views as shown in the screenshot.

![s1](https://github.com/user-attachments/assets/38cde147-8549-465f-82fa-a02cf0f4d3c5)



When I use EF POWER TOOL I use the parameters as below, the test connection works but at the next step (where I think it should list the tables or extract parameters for EF) it gives me an error

![s2](https://github.com/user-attachments/assets/b8b1c531-47d2-47ef-8c43-20580a05c1e4)

![s3](https://github.com/user-attachments/assets/8e58f0e0-10fd-49b3-b412-bc87b50bbb88)

**Comment by davidec** [comment]
If I select EF7 WORK!

is it a problem about EF 8 ??

**Comment by ErikEJ** [comment]
Maybe an issue with the EF Core 8 provider?

**Comment by alexkeh** [comment]
The error is an [ORA-28040: The database does not accept your client's authentication protocol; login denied.](https://docs.oracle.com/en/error-help/db/ora-28040/?r=23ai)

This would allow EFC7 to connect, but EFC8 not to if EFC7 is using ODP.NET 21c and EFC8 is using ODP.NET 23ai.

In ODP.NET 23ai, the backwards compatibility with older password verifiers was restricted. That is to encourage admins to use a newer, more robust verifier, which are harder to hack. If the DB 19c server was upgraded from an earlier Oracle version that used an old verifier and that verifier was not upgraded, then I would expect this error. Verifiers can keep their compatibility with DBs as old as version 8. The reason for this backwards compatibility is that not all client apps are upgraded to new versions at the same time. Thus, the DBA needs to keep using the lowest commonly used verifier version.

Typically, to solve this problem, you can set [Allowed Logon Version Client](https://docs.oracle.com/en/database/oracle/oracle-database/23/odpnt/featAllowedLogonVersionClientSupport.html#GUID-0BD35B7D-9D66-4D0A-8CC9-5DA99AD73138) to the version you need. You can set this in your sqlnet.ora file. If you don't know which version, your DBA should know.

Alternatively, you can try the ODP.NET 21c EF Core 8 provider to connect instead of ODP.NET 23ai if EF Core Power Tools allow swapping of provider versions.

On NuGet, the latest [Oracle EFC8 21c version is 8.21.60](https://www.nuget.org/packages/Oracle.EntityFrameworkCore/8.21.160).

**Comment by SEFINHN-UIT** [comment]
Hi everyone, I have the same problem, I documented it in this issue [#2769 (not solved)](https://github.com/ErikEJ/EFCorePowerTools/issues/2769) unfortunately the suggestions do not solve the problem. 

**[ErickEJ](https://github.com/ErikEJ), please: what can be done?**

Error [ORA-28040](https://docs.oracle.com/en/error-help/db/ora-28040/?r=19c)


> Before opening the connection, is there a way to add the following [code](https://docs.oracle.com/en/database/oracle/oracle-database/23/odpnt/ConfigurationAllowedLogonVersionClient.html#GUID-957B7ADA-C3CB-41B0-92DD-176130B1205C):
```c#
OracleConfiguration.SqlNetAuthenticationServices = "none";
OracleConfiguration.SqlNetAllowedLogonVersionClient = OracleAllowedLogonVersionClient.Version11;
```

**Comment by alexkeh** [comment]
@SEFINHN-UIT 
You can set SQLNET.ALLOWED_LOGON_VERSION and SQLNET.ALLOWED_LOGON_VERSION_CLIENT in the sqlnet.ora configuration file instead of making .NET code changes.

**Comment by SEFINHN-UIT** [comment]
> Puede establecer SQLNET. ALLOWED_LOGON_VERSION y SQLNET. ALLOWED_LOGON_VERSION_CLIENT en el archivo de configuración sqlnet.ora en lugar de realizar cambios en el código .NET.

Thanks for your help @alexkeh, I'm a little frustrated. I managed to get it working, but this month it crashes, and the only change the DBA made was enabling and disabling the SEC_CASE_SENSITIVE_LOGON parameter.

**Comment by alexkeh** [comment]
You shouldn't experience a crash. Can you enable ODP.NET tracing at trace level 7 and share the trace? That should tell me more about why you experience a crash.

**Comment by SEFINHN-UIT** [comment]
Thank you @alexkeh, it was not possible to enable ADO.NET tracing for EFCPT. But we did manage to fix the error by creating the sqlnet.ora file with the parameters: 

> SQLNET. ALLOWED_LOGON_VERSION y SQLNET. ALLOWED_LOGON_VERSION_CLIENT.

Our problem was that in the connection options we were not using the TNS_NAME.ora file, we were using a Basic connection string, and EFCPT does not allow us to programmatically inject code to enable login compatibility with older versions from Oracle. 

Once we changed the connection options to use TNS_NAME.ora and the SQLNET.ora file was created in the same path with the parameters suggested by you and [the oracle documentation](https://docs.oracle.com/en/database/oracle/oracle-database/18/spuss/check-for-sqlnet-allowed-logon-version-parameter-behavior.html), the information from the EFCPT tables was loaded correctly.
