### ISSUE TITLE
Is there support for synchronous stored procedures via cli?

### ISSUE THREAD

**Issue by mtaeubert-tmn** [ErikEJ/EFCorePowerTools#2556]
I see in the documentation when using the UI it is possible to scaffold synchronous stored procedures by setting "UseAsyncStoredProcedureCalls": false.

However, I'm trying to do this via the cli and this setting does not seem to be implemented there.  I tried something like code-generation/use-async-stored-procedure-calls, but it does not work. 

I'm not sure if this setting is just not implemented via cli yet or if I just couldn't find what its name is there.

**Comment by ErikEJ** [comment]
It is not implemented in the CLI, which is only for modern, async apps. 😎

**Comment by ErikEJ** [comment]
Closing as by design

If you like my free tools, I would be very grateful for a rating/review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details) and/or a [one-time or monthly sponsorship](https://github.com/sponsors/ErikEJ?frequency=one-time&sponsor=ErikEJ)

**Comment by mtaeubert-tmn** [comment]
Thanks for the reply. We'll try to just generate them with a T4 template then or see if we can refactor some of our libraries to also be able to handle async :)
