### ISSUE TITLE
Add compare operation helper for EFCorePowerTools-Handlebars

### ISSUE THREAD

**Issue by 56109403** [ErikEJ/EFCorePowerTools#333]
For example, I have below code generate by EFCorePowerTools C# Handlebars template (Reverse Engineering).
Now I want to remove line "public int Id { get; set; }" becase Id property already inherrit from class Entity.
Can this tools have some condition or compare helper registered for Handlebars by default, then update the Handlebars template can skip this property easily.

public partial class EXP_Area : Entity
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int? AreaType { get; set; }
        public int? FreightForecastID { get; set; }
        public string CountryCode { get; set; }
    }

Handlebars.registerHelper("compare", function (v1, v2, option) {
	if (v1 === v2) {	
		return option.fn(this);
	} else {
		return option.inverse(this);
	}
});

**Comment by ErikEJ** [comment]
I doubt it is possible - @tonysneed ??

**Comment by ErikEJ** [comment]
This is only possible if you call scaffolding yourself. Also, you are mixing "Database First" with domain modelling,

**Comment by tonysneed** [comment]
Yes, to had Handlebars helpers you need to use the EF Core CLI from the command line, rather than going through the Power Tools. In that case, you would add add a class to your project that implements IDesignTimeServices, where you would register your helper. See https://github.com/TrackableEntities/EntityFrameworkCore.Scaffolding.Handlebars/blob/master/README.md.
