### ISSUE TITLE
How to inherit from different base classes

### ISSUE THREAD

**Issue by janissimsons** [ErikEJ/EFCorePowerTools#579]
How can I inherit from different base classes?
I have 3 dbcontexts, each has ~50 tables, and I have 3 base classes respectively.
The first set of entities should inherit from the first base class, the second set of entities from second base class and so on.

How can I accomplish this? 
If I use handlebar templates, it only allows inheriting from one base class for all entities in the project.

**Comment by ErikEJ** [comment]
This is not possible. It sounds like you are mixing database first and domain modelling...

**Comment by janissimsons** [comment]
Yes, I am integrating external databases, which I have no control over, but I have to work with their data in my application. So I am reverse engineering their entities, and most of them have common columns, which I can extract to a base class.
So I guess my only choice is to set the base class in handlebar template then regenerate only one set of entities, then change the template and regenerate the next set of entities.. a bit cumbersome, but I guess it's still easier than writing all those classes manually.

**Comment by ErikEJ** [comment]
@janissimsons Yes, that would work, but would be slightly cumbersome, agree.

**Comment by lloydkevin** [comment]
@janissimsons have you succeeded in doing this? If so, I've love to see your solution.

**Comment by coldacid** [comment]
I have a similar issue, but it's one generic base type and I need to be able to set the type param to the type of the property mapped to the primary key for each entity.

**Comment by ErikEJ** [comment]
@coldacid I need an example, i do not understand.

Maybe you are mixing db first and domain modelling?

**Comment by coldacid** [comment]
@ErikEJ I am in the unfortunate position of having to use a certain base class for entities against an existing database that I don't really have control over, yeah. So each entity class in this DB context needs to inherit from `BaseEntity<TPrimaryKey>` for the rest of this system to work. That base class declares the `Id` property itself, as well. Since the primary key columns are locked-in with EFPT, I can't simply have a file that goes `partial class MyEntityA : BaseEntity<int> {}` etc. because the declaration of `Id` in the generated class doesn't `override` the base declaration of the property.

I think my use case could be satisfied by pushing one or both of these tokens into Handlebars, namely:

* a token for the entity class template specifying the C# type of the primary key column, when one exists
* a token for the entity property template flagging if the current property is a primary key property

With that, I can make use of the Handlebars templates to either inherit directly in the generated code from the base class, or add the `override` keyword on the primary key property and have a file I manage myself for adding the inheritance to each entity class.

**Comment by ErikEJ** [comment]
You can only do that if you implement your own DesignContextFactory, not possible with Power Tools, as they know nothing of your codebase.

**Comment by coldacid** [comment]
Actually, I wonder if that's doable in EntityFrameworkCore.Scaffolding.Handlebars itself. It needs to understand the model at least to a certain point in order to process the templates, right? Then it should be able to tell which property gets KeyAttribute and pump that info in, given that I see said attribute shows up in the generated code on the entity classes.

**Comment by ErikEJ** [comment]
Yes, that library can hook into your own code.
