### ISSUE TITLE
Allow to Reverse Engineer without a root namespace

### ISSUE THREAD

**Issue by HSchwichtenberg** [ErikEJ/EFCorePowerTools#795]
It should be allowed to leave the box "Namespace" empty and just have a namespace for Entity Types (e.g. "BO") and Context (e.g. "DA"). This is possible with "Scaffold-DbContext". It should be a very easy change in your code. 

### Steps to reproduce
![image](https://user-images.githubusercontent.com/3673169/108415298-a6a72a00-722d-11eb-94a3-97ade5d798f4.png)

### Further technical details
EF Core Power Tools version: 2.5.454.0
Database engine: any
Visual Studio version: Visual Studio 2019 16.8

**Comment by ErikEJ** [comment]
So if nothing specified in Namespace, both Entity and Context name space must be supplied?

**Comment by HSchwichtenberg** [comment]
Yes, that would allow different namespaces with no common root.

**Comment by ErikEJ** [comment]
Fixed in latest daily, please let me know if that works for you.

**Comment by ErikEJ** [comment]
Ping?

**Comment by HSchwichtenberg** [comment]
Thank you, Eric. I will have a look at it next week.

Erik Ejlskov Jensen <notifications@github.com> schrieb am Sa., 20. Feb.
2021, 08:38:

**Comment by KernelLeak** [comment]
I just reverse engineered a database and was looking for a way to place both the entities and the context into the same namespace, so leaving the root namespace empty and specifying the same namespace for entities and the context worked fine.

The only problem was that when I re-did the reverse engineering step, the empty root namespace was automatically replaced by the default namespace again, so that I now have to clear out the root namespace field every time - would it be possible to persist my choice of no root namespace somehow?

**Comment by ErikEJ** [comment]
@KernelLeak This does not really seem related to this closed issue.
Please post a new issue, preferably with your efpt.config.json file contents included.
