### ISSUE TITLE
Improve reveng performance

### ISSUE THREAD

**Issue by ErikEJ** [ErikEJ/EFCorePowerTools#828]
- [x] Avoid delete / copy of tool on every execution
- [ ] Cache DatabaseModel based on checksum/hash of connection string - to avoid call on code generation 
- [ ] Only cache full model
- [ ] Remove all non-selected tables from cache after reading it.

**Comment by ErikEJ** [comment]
@sm15455 Any thoughts?

**Comment by sm15455** [comment]
I don't remember. When is the DatabaseModel calculated? Before object selection and before code generation? In this case I think caching is a good idea. 
I should investigate the code to find other improvement points. As soon as I finish localization I can give it a look.

**Comment by ErikEJ** [comment]
Right now it is calculated twice, once when getting the table list and once when generating code. And it performs multiple queries against the database.

**Comment by sm15455** [comment]
Then caching between the two phases is a good idea. 
As a plus, it would be great if we could find a way to detect if database schema has changed since the last time we read it (so we can safely reuse cached model). Maybe a query on some system table or view could work, but it would require knowledge of each database type.

**Comment by ErikEJ** [comment]
Looks like the constant delete and unzip of the tool also had some impact - that is fixed now.

I will investigate the idea about light weight detection of schema changes.

**Comment by ErikEJ** [comment]
https://www.google.com/amp/s/blog.sqlauthority.com/2014/07/07/sql-server-ssms-schema-change-history-report/

**Comment by sm15455** [comment]
Great! To recap:
when we read the model before object selection we look for a cached version. If It exists, we check if it's stale or not. If it's updated we reuse it, otherwise we calculate the model and cache it. If the cached version doesn't exist, we calculate and cache it. If the database doesn't support change detection likes SQL server, we always calculate the model and cache it.
When we read the model before code generation, we use cached model.

Is this correct?

**Comment by ErikEJ** [comment]
Yes, initially without change detection against RDBMS.

One of the interesting points is the definition of stale - thinking about 120 seconds, also considering making it user configurable.

**Comment by sm15455** [comment]
Without change detection, we can't truly detect if it's stale or not. A time span can be a good alternative. We could also add a "refresh" button in the object selection page so the user can reload objects from database if the list is stale. I happened to need it in the past. I had the object selection page open and I modified the dev database. I had to close the wizard and restart from the beginning. Having a refresh button would have been useful but I understand it's an edge case.
